# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title : アルブログ
tagline: "CoZe's stuff"
author :
  name : Arda Karaduman
  email :
  github : c0ze
  twitter : ardakaraduman

description: > # this means to ignore newlines until "baseurl:"
  Some ramblings, about all kinds of stuff. Mostly geeky.

baseurl: "" # the subpath of your site, e.g. /blog
url: http://blog.coze.org
twitter_username: ardakaraduman
github_username:  c0ze

# Build settings
markdown: redcarpet
redcarpet:
   extensions:
     - "disable_indented_code_blocks"
     - "tables"
     - "fenced_code_blocks: true"

gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-slim

slim:
  pretty: true
  format: html5

paginate: 5

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "vendor", "Gemfile*"]

assets:
  digest: false
  prefix: "/assets"
  assets:
    - "*.png"
    - "*.jpg"
  sources:
    - assets

sass:
  style: compressed

mini_magick:
  galleries_path: "assets/images/galleries"
  thumbnail_dir: "thumbs"
  options:
    - thumbnail: "140x140^"
    - crop: "140x140-0x0"
