# --- Serving options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

title : アルブログ
tagline: "CoZe's stuff"
author :
  name : Arda Karaduman
  email :
  github : c0ze
  twitter : ardakaraduman
  facebook: karaduman.arda
  linkedin: "in/ardakaraduman"
  stackoverflow: yourlink  # eg. "3943160/daattali"

description: > # this means to ignore newlines until "baseurl:"
  Some ramblings, about all kinds of stuff. Mostly geeky.

baseurl: "" # the subpath of your site, e.g. /blog
url: http://blog.coze.org

# --- Navigation bar options --- #

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar-icon.png"

# List of links in the navigation bar
navbar-links:
  Home: ""
  About Me: "aboutme"
  CV: "http://arda.karaduman.web.tr"

# --- Footer options --- #

# Select which links to show in the footer
footer-links-active:
  rss: true
  facebook: true
  email: false
  twitter: true
  github: true
  linkedin: true
  stackoverflow: false

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "blog.coze.org"  # eg. "deanattali.com/beautiful-jekyll"

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
#disqus: ""

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-56175514-2"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Japan/Tokyo"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "default"
      show-avatar: true

gems:
  - jekyll-assets
  - jekyll-paginate

assets:
  digest: false
  prefix: "/assets"
  assets:
    - "*.png"
    - "*.jpg"
  sources:
    - assets

sass:
  style: compressed

mini_magick:
  galleries_path: "assets/images/galleries"
  thumbnail_dir: "thumbs"
  options:
    - thumbnail: "140x140^"
    - crop: "140x140-0x0"

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Vagrantfile
  - vendor

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."
  
# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
