title = "Coze's Blog"
baseurl = "https://blog.coze.org/"
languageCode = "en-us"
theme = "hyde"
tags = ["dev", "retro", "music", "geek"]
googleAnalytics = "UA-56175514-2"
disqusShortname = "coze"

[params]
    description = "musings and ramblings from the land of the rising sun"
